spring:
  datasource:
    url: jdbc:mysql://database-1.cg1nz60tpaa5.us-east-1.rds.amazonaws.com:3306/userdb?createDatabaseIfNotExist=true
    username: admin
    password: DemonSlayer$^46
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties-hibernate-dialect: org.hibernate.dialect.MySQL8Dialect

  error:
    whitelabel:
      enabled: false
